In [3]:
import pandas as pd 
import seaborn as sns

In [4]:
insurance = pd.read_csv("insurance.csv")

In [5]:
# check for null values
insurance.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
insurance

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [7]:
#for median
insurance.median(numeric_only=True)

age           39.000
bmi           30.400
children       1.000
charges     9382.033
dtype: float64

In [9]:
#for quartiles(25%,50%) median, and 75%
insurance.quantile ([0.25,0.5,0.75], numeric_only = True)

       age       bmi  children       charges
0.25  27.0  26.29625       0.0   4740.287150
0.50  39.0  30.40000       1.0   9382.033000
0.75  51.0  34.69375       2.0  16639.912515

In [12]:
df = pd.read_csv("insurance.csv")
total_sum = df['charges'].sum()
print("sum:", total_sum)

sum: 17755824.990759